# Generated by Django 5.1 on 2024-08-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("forename", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=100)),
                ("points", models.IntegerField()),
                ("assists", models.IntegerField()),
                ("rebounds", models.IntegerField()),
                ("steals", models.IntegerField()),
                ("blocks", models.IntegerField()),
                ("turnover", models.IntegerField()),
                ("three", models.IntegerField()),
                ("three_made", models.IntegerField()),
                ("two", models.IntegerField()),
                ("two_made", models.IntegerField()),
                ("one", models.IntegerField()),
                ("one_made", models.IntegerField()),
                ("efficiency", models.IntegerField()),
            ],
        ),
    ]
