# Generated by Django 5.1 on 2024-08-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0002_remove_player_assists_remove_player_blocks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="time",
            field=models.IntegerField(default=0),
        ),
    ]
